In [31]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from mlxtend.classifier import Perceptron
from sklearn.model_selection import train_test_split

digits = load_digits()
sc = StandardScaler()
sc.fit(digits.data)

print(digits.data.shape)


(1797, 64)


In [32]:
print(digits.images.shape)

(1797, 8, 8)


In [33]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [34]:
digits.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

# Valores maximos y minimos 


In [35]:
print(np.amax(digits.data))
print(np.amin(digits.data))

16.0
0.0


# Normalizacion

In [0]:

MNIST = {i: [] for i in range(10)}

for label, data in zip(digits.target, sc.transform(digits.data)):

    MNIST[label].append(data.flatten())
    

In [0]:

#print(MNIST)

def load_mnist(a,b):
    temp_a = MNIST[a]
    temp_b = MNIST[b]

    return len(temp_a), len(temp_b), np.concatenate((temp_a,temp_b))

In [38]:
acum = 0
for i in range(10):
  print (len (MNIST[i]))
  acum += len(MNIST[i])

print(acum)

178
182
177
183
181
182
181
179
174
180
1797


#Entrenamiento con Mlxtend

In [0]:
load_mnist(0,9)
per3 = Perceptron(eta=0.05, epochs=100, random_seed=1, print_progress=3)
#type(MNIST[1])

In [40]:
a,b, XX = load_mnist(0,9)

YY = np.array([0] * a + [1] * b)


per3.fit(XX,YY)


/usr/local/lib/python3.6/dist-packages/mlxtend/_base/_classifier.py:19: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if not np.issubdtype(y[0], int):
Iteration: 100/100 | Elapsed: 0:00:01 | ETA: 0:00:00

In [42]:
a

178

In [44]:
b

180

In [45]:
XX

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.88456568, ..., -0.63808502,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.46382335, ..., -0.46856421,
        -0.5056698 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.25345218, ...,  0.37903986,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.25345218, ...,  0.37903986,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752]])

In [0]:
per3.score(XX,YY)

1.0

In [0]:
X_train, X_test, y_train, y_test = train_test_split(XX, YY, test_size=0.3, random_state=42)

In [0]:
per4 = Perceptron(eta=0.05, epochs=100, random_seed=1, print_progress=3)
per4.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/mlxtend/_base/_classifier.py:19: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if not np.issubdtype(y[0], int):
Iteration: 100/100 | Elapsed: 0:00:00 | ETA: 0:00:00

In [0]:
per4.score(X_test, y_test)

0.9907407407407407

#Que tendria que hacer para realizar clasificacion multiclase ocupando varios perceptrones simples? 
R: se podria aplicar el la letra que se desea decifrar con un todos contra todos. Contabilizando cuales son las letras que mas llega detectarse en los diferentes modelos, finalmente seleccionando el que mas haya sido detectado.

In [0]:
class Rosenblatt(object):

    def __init__(self, no_of_inputs=64, threshold=10, learning_rate=0.25):
        self.threshold = threshold
        self.learning_rate = learning_rate
        self.weights = np.zeros(no_of_inputs + 1)
        self.score = []
           
    def predict(self, inputs):
        summation = np.dot(inputs, self.weights[1:]) + self.weights[0]
        if summation > 0:
          activation = 1
        else:
          activation = -1            
        return activation

    def train(self, training_inputs, labels):

        for _ in range(self.threshold):
            
            for inputs, label in zip(training_inputs, labels):
                prediction = self.predict(inputs)
                self.weights[1:] += self.learning_rate * (label - prediction) * inputs
                self.weights[0] += self.learning_rate * (label - prediction)
    
    def rate(self, XX, YY):
        total = 0
        for i, element in enumerate(XX):
            total += self.predict(element) == YY[i]
        
        return total / len(XX)


#Ocupando el algoritmo de Rosenblatt para generar 10 perceptrones, uno por cada dı́gito. La idea de cada perceprón es que sea entrenado como uno contra el resto

In [0]:
perceptrons = {i:[] for i in range(10)}

for i in range(10):
    print("*"*10)
    for j in range(10):

        if j == i:
            continue
        
        percep = Rosenblatt()
        a,b, XX = load_mnist(i,j)

        YY = np.array([-1] * a + [1] * b)

        percep.train(XX,YY)
        
        print(f'precision de {i} con {j} es: {percep.rate(XX,YY)}')
    print("*"*10,'\n\n')
        

**********
precision de 0 con 1 es: 1.0
precision de 0 con 2 es: 1.0
precision de 0 con 3 es: 1.0
precision de 0 con 4 es: 1.0
precision de 0 con 5 es: 1.0
precision de 0 con 6 es: 1.0
precision de 0 con 7 es: 1.0
precision de 0 con 8 es: 1.0
precision de 0 con 9 es: 1.0
********** 


**********
precision de 1 con 0 es: 1.0
precision de 1 con 2 es: 1.0
precision de 1 con 3 es: 1.0
precision de 1 con 4 es: 1.0
precision de 1 con 5 es: 1.0
precision de 1 con 6 es: 1.0
precision de 1 con 7 es: 1.0
precision de 1 con 8 es: 0.9719101123595506
precision de 1 con 9 es: 1.0
********** 


**********
precision de 2 con 0 es: 1.0
precision de 2 con 1 es: 1.0
precision de 2 con 3 es: 1.0
precision de 2 con 4 es: 1.0
precision de 2 con 5 es: 1.0
precision de 2 con 6 es: 1.0
precision de 2 con 7 es: 1.0
precision de 2 con 8 es: 1.0
precision de 2 con 9 es: 1.0
********** 


**********
precision de 3 con 0 es: 1.0
precision de 3 con 1 es: 1.0
precision de 3 con 2 es: 1.0
precision de 3 con 4 es: 1.0


#Haciendo split de los datos 70% entrenamiento y 30% pruebas

In [0]:
perceptrons = {i:[] for i in range(10)}

for i in range(10):
    print("*"*10)
    for j in range(10):

        if j == i:
            continue
        
        percep = Rosenblatt()
        a,b, XX = load_mnist(i,j)

        YY = np.array([-1] * a + [1] * b)
        X_train, X_test, y_train, y_test = train_test_split(XX, YY, test_size=0.3, random_state=42)
        percep.train(X_train,y_train)
        
        print(f'precision de {i} con {j} es: {percep.rate(X_test,y_test)}')
    print("*"*10,'\n\n')
        



**********
precision de 0 con 1 es: 1.0
precision de 0 con 2 es: 1.0
precision de 0 con 3 es: 1.0
precision de 0 con 4 es: 0.9907407407407407
precision de 0 con 5 es: 1.0
precision de 0 con 6 es: 1.0
precision de 0 con 7 es: 0.9907407407407407
precision de 0 con 8 es: 1.0
precision de 0 con 9 es: 1.0
********** 


**********
precision de 1 con 0 es: 1.0
precision de 1 con 2 es: 1.0
precision de 1 con 3 es: 1.0
precision de 1 con 4 es: 0.9908256880733946
precision de 1 con 5 es: 1.0
precision de 1 con 6 es: 0.9724770642201835
precision de 1 con 7 es: 0.9908256880733946
precision de 1 con 8 es: 0.9626168224299065
precision de 1 con 9 es: 1.0
********** 


**********
precision de 2 con 0 es: 0.9906542056074766
precision de 2 con 1 es: 1.0
precision de 2 con 3 es: 0.9907407407407407
precision de 2 con 4 es: 1.0
precision de 2 con 5 es: 1.0
precision de 2 con 6 es: 0.9907407407407407
precision de 2 con 7 es: 1.0
precision de 2 con 8 es: 0.9339622641509434
precision de 2 con 9 es: 1.0
******

Sólo faltó esto:

A partir del punto anterior, tomando los 10 perceptrones, considere alguna forma que permita
calcular la etiqueta de la imagen de algún dı́gito introducido.

Aquí debes tomar cualquier elemento del conjunto de prueba y entre los 10 perceptrones deben "ponerse de acuerdo" y decidir a qué digito corresponde.



**Todo lo demás está bien.**
